In [1]:
# combine all the machine learning methods here and then export using joblib, test it and upload to heroku

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("D:/BC3409 AI In Accounting & Finance/Individual assignment/CreditCardDefault(balance).csv")

In [4]:
print(df)

           income        age          loan  default
0     66155.92510  59.017015   8106.532131        0
1     34415.15397  48.117153   6564.745018        0
2     57317.17006  63.108049   8020.953296        0
3     42709.53420  45.751972   6103.642260        0
4     66952.68885  18.584336   8770.099235        1
...           ...        ...           ...      ...
3423  60903.19173  21.933924  10367.081890        1
3424  62235.64470  25.033016   8083.900063        1
3425  25597.85059  26.350344   3810.110335        1
3426  48164.19497  23.141976   6529.652892        1
3427  33055.80863  26.289612   5351.851138        1

[3428 rows x 4 columns]


In [5]:
df = df.dropna()

In [6]:
for i in df.columns:
    df1 = pd.to_numeric(df[i], errors='coerce')
    df = df[df1.notnull()]

In [7]:
print(df)

           income        age          loan  default
0     66155.92510  59.017015   8106.532131        0
1     34415.15397  48.117153   6564.745018        0
2     57317.17006  63.108049   8020.953296        0
3     42709.53420  45.751972   6103.642260        0
4     66952.68885  18.584336   8770.099235        1
...           ...        ...           ...      ...
3423  60903.19173  21.933924  10367.081890        1
3424  62235.64470  25.033016   8083.900063        1
3425  25597.85059  26.350344   3810.110335        1
3426  48164.19497  23.141976   6529.652892        1
3427  33055.80863  26.289612   5351.851138        1

[3428 rows x 4 columns]


In [8]:
df.corr()

income       age      loan   default
income   1.000000 -0.028192  0.556173 -0.012761
age     -0.028192  1.000000 -0.247657 -0.653537
loan     0.556173 -0.247657  1.000000  0.508285
default -0.012761 -0.653537  0.508285  1.000000

In [9]:
y = df.loc[:,["default"]]
x = df.loc[:,["income", "age", "loan"]]

In [10]:
print(df)

           income        age          loan  default
0     66155.92510  59.017015   8106.532131        0
1     34415.15397  48.117153   6564.745018        0
2     57317.17006  63.108049   8020.953296        0
3     42709.53420  45.751972   6103.642260        0
4     66952.68885  18.584336   8770.099235        1
...           ...        ...           ...      ...
3423  60903.19173  21.933924  10367.081890        1
3424  62235.64470  25.033016   8083.900063        1
3425  25597.85059  26.350344   3810.110335        1
3426  48164.19497  23.141976   6529.652892        1
3427  33055.80863  26.289612   5351.851138        1

[3428 rows x 4 columns]


In [11]:
from scipy import stats
import numpy as np

In [12]:
# Normalisation

In [13]:
from sklearn import preprocessing

In [14]:
scaler = preprocessing.MinMaxScaler()

In [15]:
name = df.columns

In [16]:
d = scaler.fit_transform(df)

In [17]:
df = pd.DataFrame(d, columns = name)

In [18]:
print(df)

        income       age      loan  default
0     0.923176  0.957431  0.588837      0.0
1     0.288122  0.863786  0.476827      0.0
2     0.746334  0.992579  0.582620      0.0
3     0.454072  0.843466  0.443328      0.0
4     0.939117  0.610057  0.637045      1.0
...        ...       ...       ...      ...
3423  0.818082  0.638835  0.753066      1.0
3424  0.844741  0.665460  0.587193      1.0
3425  0.111709  0.676778  0.276703      1.0
3426  0.563206  0.649214  0.474278      1.0
3427  0.260925  0.676256  0.388711      1.0

[3428 rows x 4 columns]


In [19]:
# Categorical Input

In [20]:
df['default'] = df.default.astype('category')

In [21]:
# Logistic Regression

In [22]:
from sklearn import linear_model

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [25]:
model = linear_model.LogisticRegression()

In [26]:
model.fit(x_train,y_train)

C:\Users\hahang\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [27]:
pred = model.predict(x_train)

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
cm = confusion_matrix(y_train, pred)

In [30]:
print(cm)

[[1036  136]
 [ 208 1019]]


In [31]:
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))

In [32]:
print(accuracy)

0.8566069195498124


In [33]:
pred = model.predict(x_test)

In [34]:
cm = confusion_matrix(y_test, pred)

In [35]:
print(cm)

[[468  74]
 [ 77 410]]


In [36]:
accuracy1 = (cm[0,0] + cm[1,1])/sum(sum(cm))

In [37]:
print(accuracy1)

0.8532555879494655


In [38]:
# Decision Tree

In [39]:
from sklearn import tree

In [40]:
model = tree.DecisionTreeClassifier(max_depth=8)

In [41]:
model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=8)

In [42]:
pred = model.predict(x_test)

In [43]:
cm = confusion_matrix(y_test, pred)

In [44]:
print(cm)

[[535   7]
 [  5 482]]


In [45]:
accuracy2 = (cm[0,0] + cm[1,1])/sum(sum(cm))

In [46]:
print(accuracy2)

0.9883381924198251


In [47]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(x_train,y_train)

In [48]:
for i in range (20):
    model = tree.DecisionTreeClassifier(max_depth=i+1)
    model.fit(x_train1, y_train1)
    pred = model.predict(x_test1)
    cm = confusion_matrix(y_test1, pred)
    accuracy3 = (cm[0,0] + cm[1,1])/(sum(sum(cm)))
    print(i+1)
    print(accuracy3)
    print("========================")

1
0.845
2
0.9233333333333333
3
0.925
4
0.965
5
0.9783333333333334
6
0.98
7
0.9833333333333333
8
0.985
9
0.9833333333333333
10
0.9833333333333333
11
0.9816666666666667
12
0.9833333333333333
13
0.9816666666666667
14
0.9833333333333333
15
0.98
16
0.9833333333333333
17
0.9816666666666667
18
0.9816666666666667
19
0.9816666666666667
20
0.9833333333333333


In [49]:
from sklearn.model_selection import GridSearchCV

In [50]:
model = tree.DecisionTreeClassifier()

In [51]:
g = GridSearchCV(estimator=model, param_grid=dict(max_depth = [i for i in range(1,20)]))

In [52]:
g = g.fit(x_train,y_train)

In [53]:
g.best_params_

{'max_depth': 11}

In [54]:
h = GridSearchCV(estimator=model, param_grid=dict(min_samples_split = [i for i in range(1,20)]))

In [55]:
h = h.fit(x_train,y_train)

C:\Users\hahang\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\hahang\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\hahang\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\hahang\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\hahang\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. 

In [56]:
h.best_params_

{'min_samples_split': 4}

In [57]:
model = tree.DecisionTreeClassifier(min_samples_split=2)
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [58]:
pred = model.predict(x_test)

In [59]:
cm = confusion_matrix(y_test,pred)

In [60]:
print(pred)

[0 1 1 ... 1 1 0]


In [61]:
print(cm)

[[535   7]
 [  5 482]]


In [62]:
accuracy4 = (cm[0,0] + cm[1,1])/(sum(sum(cm)))
print(accuracy4)

0.9883381924198251


In [63]:
# Random Forest

In [64]:
from sklearn import ensemble
model = ensemble.RandomForestClassifier()

In [65]:
model.fit(x_train, y_train)

C:\Users\hahang\AppData\Local\Temp/ipykernel_7076/940050797.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x_train, y_train)


RandomForestClassifier()

In [66]:
pred = model.predict(x_test)

In [67]:
cm = confusion_matrix(y_test, pred)

In [68]:
print(pred)

[0 1 1 ... 1 1 0]


In [69]:
print(cm)

[[536   6]
 [  2 485]]


In [70]:
accuracy5 = (cm[0,0] + cm[1,1])/(sum(sum(cm)))
print(accuracy5)

0.9922254616132167


In [71]:
# XGBoost

In [72]:
model = ensemble.GradientBoostingClassifier()
model.fit(x_train, y_train)

C:\Users\hahang\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GradientBoostingClassifier()

In [73]:
pred = model.predict(x_test)
cm = confusion_matrix(y_test, pred)

In [74]:
print(pred)

[0 1 1 ... 1 1 0]


In [75]:
print(cm)

[[533   9]
 [  2 485]]


In [76]:
accuracy6 = (cm[0,0] + cm[1,1])/(sum(sum(cm)))
print(accuracy6)

0.989310009718173


In [77]:
# Neural Network

In [78]:
from sklearn.neural_network import MLPClassifier

In [79]:
# model works up to this point

In [80]:
model = MLPClassifier(solver='lbfgs', random_state=0, hidden_layer_sizes=(7,7)).fit(x,y)

C:\Users\hahang\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\hahang\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [81]:
# number of hidden layer is random

In [82]:
pred = model.predict(x)

In [83]:
print(pred)

[0 1 1 ... 1 1 1]


In [84]:
cm = confusion_matrix(y, pred)

In [85]:
print(cm)

[[1261  453]
 [  41 1673]]


In [86]:
accuracy7 = (cm[0,0] + cm[1,1])/(sum(sum(cm)))
print(accuracy7)

0.8558926487747958


In [87]:
# export model

In [88]:
import joblib

In [89]:
joblib.dump(model, "Default Probability")

['Default Probability']